### PR TITLE
[WIP] Successfulness

### LINKED ISSUE #4: Support determining the probability that an expression is a success
It's very common in TTRPGs that you need to meet a goal with a dice roll (less than or equal to X, greater than Y, etc.). Expressions (see #3) should support a way to determine how likely it is that it will meet a given goal. To be extensible the goal checking should probably be closure based.

CC: @LoganJohnson

### LINKED ISSUE #59: Support determining if an expression meets a success criteria
Needs to support all of the following (even in the same expression):
- Total value is within a certain range (e.g. `>= 16`, `< 3 or >= 8`).
- Individual expressions within a compound expression can force a success or failure (e.g. a `1d20` in a larger expression rolling `1` is a failure for the expression as a whole).
- Expressions can report **success**, **failure**, or **not determined**, the default being **not determined**. These values trickle up through compound expressions (related to the above point).
  - _What happens if two siblings report conflicting success results?_

### PR DESCRIPTION
**Pull request by brentleyjones**
Closes #4 and closes #59.
#### Features
- `Successfulness`, a type that represents if an expression was successful. `.Success`, `.Fail`, and `.Undetermined` are its current cases. `SuccessfulnessResultType` a type which `ExpressionResultType` conforms to, to allow all expression results to have successfulness.
  - [x] `SuccessfulnessResultType` Tests (all the expressions)
  - [ ] Playground
- `OutcomeWithSuccessfulness`, a way to represent successfulness with `ProbabilityMass`.
  - [x] Tests
- Extensions to `ProbabilityMass` specifically when using `OutcomeWithSuccessfulness`.
  - Reduce to probability regardless of successfulness
  - Reduce to probability only of successfulness
  - Map successfulness
  - Set new successfulness based on comparison with another expression
  - [x] Tests
  - [ ] Playground
- `SuccessfulnessExpression` to impose successfulness on an expression. Can of course wrap any expression and you can impose it multiple times.
  - [x] `SuccessfulnessExpression` Tests
  - [x] `SuccessfulnessExpressionResult` Tests
  - [ ] Playground
  - [ ] README Usage section

### CODE REVIEW

**Comment by brentleyjones** [comment]
I wouldn't mind a mid-PR code review. This is getting large, so as many eyes on it as possible would be good.

**Comment by JonathanHoffman** [comment]
This is pretty massive. I've skimmed over it. I'll try to look at it again later. So far so good.

**Comment by brentleyjones** [comment]
I'll be splitting that WIP commit into a bunch of smaller ones. I just didn't want to rebase constantly.

**Comment by brentleyjones** [comment]
I realized that `ProbabilityMass` doesn't work 100% with just `Successfulness` as it's outcome. I'll be writing tests for that, then onto creating distinct commits.

**Comment by brentleyjones** [comment]
The code is 99% done, so ready for another code review. I'll tweak it a small bit more (after feedback) and work on documentation next.

**Comment by brentleyjones** [comment]
I'm going to delay putting this in until #80 is done. It will be imposing some more constraints on Outcomes and I would rather change my code than have him deal with my constraints.

**Comment by brentleyjones** [comment]
I'll be getting to this Soon™ now. Probably by the 8th of November.

**Comment by brentleyjones** [comment]
I'm closing this, since I have a new branch I'll be pushing eventually. It has a new way of looking at Successfulness.

**Pull request closed without merging**
